# Generated by Django 4.0.6 on 2022-07-15 14:14

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='', upload_to=shop.models.upload_to),
        ),
    ]
