# Generated by Django 4.0 on 2024-01-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/photo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(default=2000)),
                ('mes', models.IntegerField(default=1)),
                ('empresa', models.CharField(max_length=70)),
                ('jefe_inmediato', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=30)),
                ('responsabilidades', models.TextField(max_length=50)),
                ('logros', models.TextField(max_length=50)),
                ('n_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(default=2000)),
                ('mes', models.IntegerField(default=1)),
                ('estudio', models.CharField(max_length=70)),
                ('institucion', models.CharField(max_length=50)),
                ('titulo_obtenido', models.CharField(max_length=50)),
                ('num_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.tipodocumento'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_sangre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.tiposangre'),
        ),
    ]
