# Generated by Django 4.0.6 on 2022-07-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('numero_documento', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=70)),
                ('telefono', models.IntegerField(default=0)),
                ('tipo_sangre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia_laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2000)),
                ('mes', models.IntegerField(default=1)),
                ('empresa', models.CharField(max_length=70)),
                ('jefe_inmediato', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=30)),
                ('responsabilidades', models.TextField(verbose_name='')),
                ('logros', models.TextField(verbose_name='')),
                ('n_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2000)),
                ('mes', models.IntegerField(default=1)),
                ('estudio', models.CharField(max_length=70)),
                ('institucion', models.CharField(max_length=50)),
                ('titulo_obtenido', models.CharField(max_length=50)),
                ('num_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
        ),
    ]
